// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using StudentsConsultations.Data.EF;
using System;

namespace StudentsConsultations.Data.EF.Migrations
{
    [DbContext(typeof(StudentskeKonsultacijeDbContext))]
    [Migration("20180126204802_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudentsConsultations.Data.EF.Datum", b =>
                {
                    b.Property<DateTime>("DatumKonsultacija");

                    b.HasKey("DatumKonsultacija");

                    b.ToTable("Datum");
                });

            modelBuilder.Entity("StudentsConsultations.Data.EF.Konsultacije", b =>
                {
                    b.Property<int>("StudentId");

                    b.Property<int>("NastavnikId");

                    b.Property<DateTime>("DatumKonsultacija");

                    b.Property<int>("RazlogId");

                    b.HasKey("StudentId", "NastavnikId", "DatumKonsultacija");

                    b.HasIndex("DatumKonsultacija");

                    b.HasIndex("NastavnikId");

                    b.HasIndex("RazlogId");

                    b.ToTable("Konsultacije");
                });

            modelBuilder.Entity("StudentsConsultations.Data.EF.Nastavnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ime")
                        .IsRequired();

                    b.Property<string>("Prezime")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Nastavnik");
                });

            modelBuilder.Entity("StudentsConsultations.Data.EF.Razlog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Opis");

                    b.HasKey("Id");

                    b.ToTable("Razlog");
                });

            modelBuilder.Entity("StudentsConsultations.Data.EF.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Ime")
                        .IsRequired();

                    b.Property<string>("Prezime")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("StudentsConsultations.Data.EF.Konsultacije", b =>
                {
                    b.HasOne("StudentsConsultations.Data.EF.Datum", "DatumObjekat")
                        .WithMany("Konsultacije")
                        .HasForeignKey("DatumKonsultacija")
                        .HasConstraintName("FK_Konsultacije_Datum");

                    b.HasOne("StudentsConsultations.Data.EF.Nastavnik", "Nastavnik")
                        .WithMany("Konsultacije")
                        .HasForeignKey("NastavnikId")
                        .HasConstraintName("FK_Konsultacije_Nastavnik")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("StudentsConsultations.Data.EF.Razlog", "Razlog")
                        .WithMany("Konsultacije")
                        .HasForeignKey("RazlogId")
                        .HasConstraintName("FK_Konsultacije_Razlog");

                    b.HasOne("StudentsConsultations.Data.EF.Student", "Student")
                        .WithMany("Konsultacije")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK_Konsultacije_Student")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
